#!/bin/sh
set -eu
umask 022

VERSION=${1:-}
OUT_DIR=${2:-dist}
SYFT=${SYFT:-syft}
BINARY=mqtt-raspberry-controller
PACKAGE=./cmd/mqtt-raspberry-controller

[ -n "$VERSION" ] || { printf 'usage: %s VERSION [OUT_DIR]\n' "$0" >&2; exit 2; }
./scripts/validate-version.sh "$VERSION"
command -v "$SYFT" >/dev/null 2>&1 || { printf 'Syft is required; run scripts/install-syft.sh\n' >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || { printf 'Python 3 is required to canonicalize CycloneDX SBOMs\n' >&2; exit 1; }
"$SYFT" version | grep -Eq '^Version:[[:space:]]+1\.43\.0$' || {
    printf 'Syft 1.43.0 is required\n' >&2
    exit 1
}

GO_VERSION=$(tr -d '[:space:]' <.go-version)
[ "$(GOTOOLCHAIN="go$GO_VERSION" go env GOVERSION)" = "go$GO_VERSION" ] || {
    printf 'release requires Go %s\n' "$GO_VERSION" >&2
    exit 1
}
COMMIT=$(git rev-parse HEAD)
SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH:-$(git show -s --format=%ct HEAD)}
export SOURCE_DATE_EPOCH TZ=UTC

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR" "$OUT_DIR/work"
for arch in amd64 arm64; do
    package_dir="$OUT_DIR/work/${BINARY}_${VERSION}_linux_${arch}"
    mkdir -p "$package_dir"
    CGO_ENABLED=0 GOOS=linux GOARCH="$arch" GOTOOLCHAIN="go$GO_VERSION" \
        go build -buildvcs=false -trimpath \
        -ldflags="-s -w -X main.version=$VERSION" \
        -o "$package_dir/$BINARY" "$PACKAGE"
    cp LICENSE README.md "$package_dir/"
    cp -R configs docs packaging "$package_dir/"
    archive="${BINARY}_${VERSION}_linux_${arch}.tar.gz"
    tar --sort=name --format=ustar --owner=0 --group=0 --numeric-owner \
        --mtime="@$SOURCE_DATE_EPOCH" -C "$OUT_DIR/work" \
        -cf - "$(basename "$package_dir")" | gzip -n >"$OUT_DIR/$archive"
    sbom="$OUT_DIR/${archive%.tar.gz}.sbom.cdx.json"
    "$SYFT" scan "file:$package_dir/$BINARY" \
        --output "cyclonedx-json=$sbom" \
        --source-name "$BINARY" --source-version "$VERSION" >/dev/null
    # CycloneDX serialNumber and metadata.timestamp are optional and generated
    # per invocation. Remove them and canonicalize JSON for reproducible SBOMs.
    python3 - "$sbom" "$BINARY" "$VERSION" <<'PY'
import json
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
binary = sys.argv[2]
version = sys.argv[3]
data = json.loads(path.read_text())
data.pop("serialNumber", None)
metadata = data.get("metadata", {})
metadata.pop("timestamp", None)
if isinstance(metadata.get("component"), dict):
    metadata["component"]["bom-ref"] = f"pkg:generic/{binary}@{version}"
for component in data.get("components", []):
    name = component.get("name", "")
    if component.get("type") == "file" and pathlib.PurePath(name).name == binary:
        component["name"] = binary
    if name == "github.com/AC-CodeProd/mqtt-raspberry-controller":
        component["version"] = version
        component["purl"] = f"pkg:golang/github.com/AC-CodeProd/mqtt-raspberry-controller@{version}"
path.write_text(json.dumps(data, sort_keys=True, separators=(",", ":")) + "\n")
PY
    printf '%s\n' "$VERSION" >"$OUT_DIR/${archive%.tar.gz}.version.txt"
    case "$(uname -m):$arch" in
        x86_64:amd64|amd64:amd64|aarch64:arm64|arm64:arm64)
            test "$("$package_dir/$BINARY" --version)" = "$VERSION"
            ;;
    esac
done

cat >"$OUT_DIR/RELEASE-VERIFICATION.txt" <<EOF
Release version: $VERSION
Source commit: $COMMIT
Workflow run: ${RELEASE_RUN_URL:-NOT RECORDED}
Release toolchain: go$GO_VERSION
Build: PASS (CGO_ENABLED=0, linux/amd64 and linux/arm64)
Version injection: PASS (recorded for both; executed on the builder's native architecture)
Archive checksum verification: performed by scripts/verify-release.sh
CycloneDX SBOM generation: PASS (Syft 1.43.0)
Quality gates: ${QUALITY_GATES_STATUS:-NOT RECORDED}
Broker integration and race tests: ${BROKER_TEST_STATUS:-NOT RECORDED}
Physical GPIO / Raspberry Pi smoke test: NOT RUN
Provenance attestation: generated by the release workflow for tagged public releases; not generated for private or dry-run builds
EOF

(
    cd "$OUT_DIR"
    sha256sum *.tar.gz *.sbom.cdx.json *.version.txt RELEASE-VERIFICATION.txt >SHA256SUMS
    sha256sum --check SHA256SUMS
)
rm -rf "$OUT_DIR/work"
